version: '3.7'
services:
  mongo:
    image: mongo:${MONGO_VERSION}
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network
volumes:
  mongo_data:
networks:
  mongo_network:
