version: '3.7'
services:
  mongo:
    image: ${PRIVATE_REPOSITORY}mongo:${MONGO_VERSION}
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network
  mongo-express:
    image: ${PRIVATE_REPOSITORY}mongo-express:${MONGO_EXPRESS_VERSION}
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN
    networks:
      - mongo_network
volumes:
  mongo_data:
networks:
  mongo_network:
