GET http://{{host}}:{{port}}{{context-path}}/api/v1/city/list
Content-Type: application/json

### find all ###

GET http://{{host}}:{{port}}{{context-path}}/api/v1/city/5f7d6bd47cccac7b0e1a520d/findById
Content-Type: application/json

### find by id ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1/city/new
Content-Type: application/json

{
  "code": "1000",
  "name": "Kota Bandung",
  "province": {
    "id": "5f7d6bc97cccac7b0e1a520c"
  }
}

