GET http://{{host}}:{{port}}{{context-path}}/api/v1/province/list
Content-Type: application/json

### find all ###

GET http://{{host}}:{{port}}{{context-path}}/api/v1/province/001/findById
Content-Type: application/json

### find by id ###

POST http://{{host}}:{{port}}{{context-path}}/api/v1/province/new
Content-Type: application/json

{
  "code": "2000",
  "name": "Jawa timur"
}

